version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: riddles
      MYSQL_USER: riddleuser
      MYSQL_PASSWORD: riddlepass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
